void PrintBinary(int x)
{
int Bit=128;
for(int i=0;i<8;i++,Bit>>=1)
if((x&Bit)!=0)cout<<1;else cout<<0;
cout<<endl;
}
void main()
{
setlocate(LC_ALL,"rus");
int a,b,res;
cout<<"Give me your number, baby>";
cin>>a>>b;
PrintBinary(a);
cout<<" +"<<endl;
PrintBinary(b);
res=a+b
cout<<" v"<<endl;
PrintBinary(res);
_getch();
}
